apiVersion: batch/v1
kind: Job
metadata:
  name: cram2fastq-david
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: cram2fastq-david
          image: eu.gcr.io/hmf-build/cram2fastq:david.2
          args: ["gs://hmf-cram2fastq/cram/CPCT12345678T.cram"]
      imagePullSecrets:
        - name: container-registry-reader
      restartPolicy: Never