apiVersion: batch/v1
kind: Job
metadata:
  name: cram2fastq-stef
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - ???
      imagePullSecrets:
        - name: container-registry-reader
      restartPolicy: Never