apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_POD_NAME
  labels:
    app: cram2fastq
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
        - name: VAR_POD_NAME
          image: eu.gcr.io/hmf-build/cram2fastq_pmc_with_sort:1.3
          imagePullPolicy: Always
          args: ["VAR_GCP_USER_PROJECT", "VAR_CRAM_URL", "VAR_OUTPUT_BUCKET", "VAR_SAMPLE_NAME"]
          resources:
            requests:
              memory: "55Gi"
            limits:
              memory: "55Gi"
      nodeSelector:
        pool: large-mem-pool-1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cram2fastq
              topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: reserved-pool
          operator: Equal
          value: "true"
          effect: NoSchedule
      restartPolicy: Never
