apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_POD_NAME
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: VAR_POD_NAME
          image: eu.gcr.io/hmf-build/cram2fastq:1.2
          imagePullPolicy: Always
          args: ["VAR_GCP_USER_PROJECT", "VAR_CRAM_URL", "VAR_OUTPUT_BUCKET", "VAR_SAMPLE_NAME"]
          resources:
            requests:
              memory: "32Gi"
            limits:
              memory: "32Gi"
      imagePullSecrets:
        - name: container-registry-reader
      restartPolicy: Never
