#!/usr/bin/env bash

gcp_user_project=$1 # optional new sample name
cram=$2 # can be GCP url or local file
bucket=$3 # must be the GCP url of a bucket or directory
new_name=$4 # optional new sample name

threads=$(($(grep -c processor /proc/cpuinfo) * 8 / 10 ))
samtools="samtools"
picard="picard.jar"
gsutil="gsutil"

data_base_dir="$HOME/data"
fastq_dir="${data_base_dir}/fastq"
bam=${cram/.cram/.bam}

script_name=$(basename "$0")

main() {
    info "Starting ${script_name}"

    sample=$(basename "${cram}" | cut -d"." -f1 | cut -d"_" -f1)
    gcp_out_path="${bucket}/${sample}_FASTQ"

    # sanity checks
    tool_exists_or_die "${samtools}"
    tool_exists_or_die "${gsutil}"
    file_exists_or_die "${picard}"
    [[ -n "${cram}" && -n "${bucket}" ]] || die "Expected cram and bucket argument. cram:'${cram}', bucket:'${bucket}'"
    [[ "${cram}" =~ (cram|bam)$ ]] || die "Expected 'cram' or 'bam' extension (${cram})"
    if [[ "${new_name}" != "" ]]; then
        [[ "${new_name}" =~ ^[a-zA-Z0-9\-]+$ ]] || die "New name can only contain [a-zA-Z0-9] or '-' (${new_name})"
    fi

    # the work
    mkdir -p "${fastq_dir}"

    if [[ "${cram}" =~ ^gs ]]; then
        cram_url="${cram}"
        cram="${data_base_dir}/$(basename "${cram_url}")"
        bam=${cram/.cram/.bam}
        info "URL input so downloading [${cram_url}]"
        gsutil -u "${gcp_user_project}" -mq cp "${cram_url}" "${cram}" || die "Unable to download ${cram}"
    fi

    if [[ "${cram}" =~ cram$ ]]; then
        convert_cram_to_bam "${cram}" "${bam}" || exit 1
        info "Deleting local copy of cram"
        rm "${cram}" || die "Could not delete the local copy of the cram: ${cram}"
    fi

    convert_bam_to_fastq "${bam}" "${fastq_dir}" || exit 1

    if [[ "${new_name}" != "" ]]; then
        info "Renaming compressed FASTQ files to include provided sample name"
        rename_fastq_files "${fastq_dir}" "${new_name}" || exit 1
        gcp_out_path="${bucket}/${new_name}_FASTQ"
    fi

    info "Copying FASTQ to GCP"
    ${gsutil} -u "${gcp_user_project}" -mq cp "${fastq_dir}/*.fastq.gz" "gs://${gcp_out_path}/" || die "Unable to upload FASTQ files"
    info "Output in gs://${gcp_out_path}"
    info "Finished ${script_name}"
}

rename_fastq_files() {
    local dir=$1 && shift
    local new_name=$1 && shift
    find "${dir}" -name "*.fastq.gz" | while read -r old_path; do
        old_file=$(basename "${old_path}")
        old_name=$(echo "${old_file}" | cut -d"_" -f1)
        new_file=${old_file/${old_name}/${new_name}}
        new_path="${dir}/${new_file}"
        if [[ "${old_path}" != "${new_path}" ]]; then
          mv "${old_path}" "${new_path}" || die "Could not rename FASTQ file from '${old_path}' to '${new_path}'"
          info "  Renamed ${old_file} to ${new_file}"
        fi
    done
}

convert_cram_to_bam() {
    local cram=$1 && shift
    local bam=$1 && shift

    info "Converting ${cram} to BAM"
    ${samtools} view -O bam -o "${bam}" --threads "${threads}" "${cram}" || die "Could not convert CRAM to BAM"

    info "Creating flagstat for ${cram}"
    cram_flagstat="${cram}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}" || die "Could not create flagstat for CRAM"

    info "Creating flagstat for ${bam}"
    bam_flagstat="${bam}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}" || die "Could not create flagstat for BAM"

    total_cram=$(head -1 "${cram_flagstat}" | cut -d" " -f1)
    total_bam=$(head -1 "${bam_flagstat}" | cut -d" " -f1)

    info "File ${cram_flagstat} shows ${total_cram} total reads"
    info "File ${bam_flagstat} shows ${total_bam} total reads"

    info "Running diff on flagstats"
    diff "${cram_flagstat}" "${bam_flagstat}" || die "Flagstat diff failed: check result before using downstream!!"
}

convert_bam_to_fastq() {
    local bam=$1 && shift
    local out_dir=$1 && shift

    info "Converting ${bam} to FASTQ"

    # double check format of RG/ID tags in header
    unexpected_read_group_count=$(samtools view -H "${bam}" | grep "^@RG" | grep -vcP "_L00[1-8]_" )
    if [[ "${unexpected_read_group_count}" -gt 0 ]]; then
        warn "There are RG ID header lines in BAM without the expected pattern present (_L00[1-8]_):"
        ${samtools} view -H "${bam}" | grep "^@RG"
        die "Exiting because renaming of fastq files will probably fail"
    fi

    info "Running SamToFastq for bam file: $(basename "${bam}")"
    java -Xmx31G -jar "${picard}" SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${bam}" 2>&1 \
        || die "SamToFastq failed"

    info "Renaming FASTQ files to standard format"
    find "${out_dir}" -name "*.fastq" | while read -r fastq_path; do
        old_name=$(basename "${fastq_path}")
        new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
        # Fix incorrect fastq names of the forms *_R1_.fastq and *_R2_.fastq
        new_name="${new_name//"_.fastq"/"_001.fastq"}"

        new_path="${out_dir}/${new_name}"
        if [[ "${fastq_path}" != "${new_path}" ]]; then
          mv "${fastq_path}" "${new_path}" || die "Could not rename FASTQ file to the proper name: '${fastq_path}' to '${new_name}'"
          info "  Renamed ${old_name} to ${new_name}"
        fi
    done

    info "Compressing FASTQ files in ${out_dir} (using pigz)"
    find "${out_dir}" -name "*.fastq" -exec pigz {} + || die "Could not compress FASTQ files with pigz"
}

msg() {
    local msg_type=$1 && shift
    local msg_content=$* && shift
    echo "[${msg_type}] $(date +'%y%m%d %T') - ${msg_content}"
}

tool_exists_or_die() {
    local tool=$1 && shift
    command -v "${tool}" >/dev/null 2>&1 || die "Tool '${tool}' not found"
}

file_exists_or_die() {
    local file=$1 && shift
    [[ -f "${file}" ]] || die "File '${file}' not found"
}

die() {
    msg "ERROR" "$@" >&2
    exit 1
}

warn() {
    msg "WARN" "$@" >&2
}

info() {
    msg "INFO" "$@"
}

main
