#!/usr/bin/env bash

gcp_user_project=$1 # optional new sample name
cram_or_bam=$2 # can be GCP url or local file, and CRAM or BAM
bucket=$3 # must be the GCP url of a bucket or directory
new_name=$4 # optional new sample name
sort_bam=$5 # whether to sort BAM before running SamToFastq
non_standard_input=$6  # skip fixing FASTQ file name format

threads=$(($(grep -c processor /proc/cpuinfo) * 8 / 10 ))
samtools="samtools"
picard="picard.jar"
gsutil="gsutil"

data_base_dir="$HOME/data"
fastq_dir="${data_base_dir}/fastq"

script_name=$(basename "$0")

main() {
    info "Starting ${script_name}"

    # sanity checks
    tool_exists_or_die "${samtools}"
    tool_exists_or_die "${gsutil}"
    file_exists_or_die "${picard}"
    [[ -n "${cram_or_bam}" && -n "${bucket}" ]] || die "Expected cram and bucket argument. cram:'${cram_or_bam}', bucket:'${bucket}'"
    [[ "${cram_or_bam}" =~ (cram|bam)$ ]] || die "Expected 'cram' or 'bam' extension (${cram_or_bam})"
    if [[ "${new_name}" != "" ]]; then
        [[ "${new_name}" =~ ^[a-zA-Z0-9\-]+$ ]] || die "New name can only contain [a-zA-Z0-9] or '-' (${new_name})"
    fi

    # the work
    mkdir -p "${fastq_dir}"

    if [[ "${cram_or_bam}" =~ ^gs ]]; then
        cram_or_bam_url="${cram_or_bam}"
        local_cram_or_bam="${data_base_dir}/$(basename "${cram_or_bam_url}")"
        info "URL input so downloading [${cram_or_bam_url}]"
        gsutil -u "${gcp_user_project}" -mq cp "${cram_or_bam_url}" "${local_cram_or_bam}" || die "Unable to download ${cram_or_bam_url}"
    else
        local_cram_or_bam="${cram_or_bam}"
    fi

    if [[ "${local_cram_or_bam}" =~ cram$ ]]; then
        local_cram="${local_cram_or_bam}"
        local_bam=${local_cram_or_bam/.cram/.bam}
        convert_cram_to_bam "${local_cram}" "${local_bam}" || exit 1
    else
        local_bam="${local_cram_or_bam}"
    fi

    convert_bam_to_fastq "${local_bam}" "${fastq_dir}" "${sort_bam}" "${non_standard_input}" || exit 1

    if [[ "${new_name}" != "" ]]; then
        info "Renaming compressed FASTQ files to include provided sample name"
        rename_fastq_files "${fastq_dir}" "${new_name}" || exit 1
    fi

    info "Determine GCP output bucket"
    gcp_out_path=$(determine_gcp_out_path "${bucket}" "${new_name}" "${local_bam}" "${non_standard_input}") \
        || die "Could not determine output bucket"

    info "Copying FASTQ to GCP"
    ${gsutil} -u "${gcp_user_project}" -mq cp "${fastq_dir}/*.fastq.gz" "${gcp_out_path}/" || die "Unable to upload FASTQ files"
    info "Output in ${gcp_out_path}"
    info "Finished ${script_name}"
}

rename_fastq_files() {
    local dir=$1 && shift
    local new_name=$1 && shift
    find "${dir}" -name "*.fastq.gz" | while read -r old_path; do
        old_file=$(basename "${old_path}") || die "Could not get file name of ${old_path}"
        old_file_name_end=$(echo "${old_file}" | cut -d"_" -f2-) || die "Could not get file name base of ${old_file}"
        new_file="${new_name}_${old_file_name_end}"
        new_path="${dir}/${new_file}"
        if [[ "${old_path}" != "${new_path}" ]]; then
          mv "${old_path}" "${new_path}" || die "Could not rename FASTQ file from '${old_path}' to '${new_path}'"
          info "  Renamed ${old_file} to ${new_file}"
        fi
    done
}

convert_cram_to_bam() {
    local cram=$1 && shift
    local bam=$1 && shift

    info "Converting ${cram} to BAM"
    ${samtools} view -O bam -o "${bam}" --threads "${threads}" "${cram}" || die "Could not convert CRAM to BAM"

    info "Creating flagstat for ${cram}"
    cram_flagstat="${cram}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}" || die "Could not create flagstat for CRAM"

    info "Creating flagstat for ${bam}"
    bam_flagstat="${bam}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}" || die "Could not create flagstat for BAM"

    total_cram=$(head -1 "${cram_flagstat}" | cut -d" " -f1)
    total_bam=$(head -1 "${bam_flagstat}" | cut -d" " -f1)

    info "File ${cram_flagstat} shows ${total_cram} total reads"
    info "File ${bam_flagstat} shows ${total_bam} total reads"

    info "Running diff on flagstats"
    diff "${cram_flagstat}" "${bam_flagstat}" || die "Flagstat diff failed: check result before using downstream!!"

    info "Deleting local copy of cram"
    rm "${cram}" || die "Could not delete the local copy of the cram: ${cram}"
}

convert_bam_to_fastq() {
    local bam=$1 && shift
    local out_dir=$1 && shift
    local sort_bam=$1 && shift
    local non_standard_input=$1 && shift

    info "Converting ${bam} to FASTQ"

    # double check format of RG/ID tags in header
    if [[ "${non_standard_input}" != "TRUE" ]]; then
      unexpected_read_group_count=$(${samtools} view -H "${bam}" | grep "^@RG" | grep -vcP "_L00[1-8]_" )
      if [[ "${unexpected_read_group_count}" -gt 0 ]]; then
          warn "There are RG ID header lines in BAM without the expected pattern present (_L00[1-8]_):"
          ${samtools} view -H "${bam}" | grep "^@RG"
          die "Exiting because renaming of fastq files will probably fail"
      fi
    fi

    if [[ "${sort_bam}" == "TRUE" ]]; then
      info "Sort BAM by read name"
      bam_to_convert="${bam/.bam/.sorted.bam}"
      ${samtools} sort -n -@ "${threads}" -o "${bam_to_convert}" "${bam}" || die "Could not sort BAM by read name"

      info "Delete unsorted BAM"
      rm "${bam}" || die "Could not delete the unsorted BAM: ${bam}"
    else
      info "Don't sort BAM by read name"
      bam_to_convert="${bam}"
    fi

    info "Running SamToFastq for bam file: $(basename "${bam_to_convert}")"
    java -Xmx31G -jar "${picard}" SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${bam_to_convert}" 2>&1 \
        || die "SamToFastq failed"

    info "Delete BAM"
    rm "${bam_to_convert}" || die "Could not delete the BAM: ${bam_to_convert}"

    if [[ "${non_standard_input}" != "TRUE" ]]; then
        info "Renaming FASTQ files to standard format"
        find "${out_dir}" -name "*.fastq" | while read -r fastq_path; do
            old_name=$(basename "${fastq_path}")

            dash_only_old_name="${old_name//[^_]}"
            dash_count="${#dash_only_old_name}"
            if [[ "${dash_count}" == "5" ]]; then
                new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
            elif [[ "${dash_count}" == "4" ]]; then
                new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print "SAMPLE_"$1"_"$2"_"$3"_R"$5"_"$4".fastq" }')
            else
                die "Number of dashes in ${old_name} is unexpected (i.e. not 5 or 4). Cannot rename file to standard format."
            fi

            # Fix incorrect fastq names of the forms *_R1_.fastq and *_R2_.fastq
            new_name="${new_name//"_.fastq"/"_001.fastq"}"

            new_path="${out_dir}/${new_name}"
            if [[ "${fastq_path}" != "${new_path}" ]]; then
                mv "${fastq_path}" "${new_path}" || die "Could not rename FASTQ file to the proper name: '${fastq_path}' to '${new_name}'"
                info "  Renamed ${old_name} to ${new_name}"
            fi
        done
    fi

    info "Compressing FASTQ files in ${out_dir} (using pigz)"
    find "${out_dir}" -name "*.fastq" -exec pigz {} + || die "Could not compress FASTQ files with pigz"
}

determine_gcp_out_path() {
    local bucket=$1 && shift
    local new_name=$1 && shift
    local local_bam=$1 && shift
    local non_standard_input=$1 && shift

    if [[ "${new_name}" != "" ]]; then
        sample="${new_name}"
    elif [[ "${non_standard_input}" == "TRUE" ]]; then
        file_name=$(basename "${local_bam}") || die "Could not get base file name: ${local_bam}"
        sample="${file_name%.*}"
    else
        sample=$(basename "${local_bam}" | cut -d"." -f1 | cut -d"_" -f1) || die "Could not get sample name: ${local_bam}"
    fi
    echo "gs://${bucket}/${sample}_FASTQ"
}

msg() {
    local msg_type=$1 && shift
    local msg_content=$* && shift
    echo "[${msg_type}] $(date +'%y%m%d %T') - ${msg_content}"
}

tool_exists_or_die() {
    local tool=$1 && shift
    command -v "${tool}" >/dev/null 2>&1 || die "Tool '${tool}' not found"
}

file_exists_or_die() {
    local file=$1 && shift
    [[ -f "${file}" ]] || die "File '${file}' not found"
}

die() {
    msg "ERROR" "$@" >&2
    exit 1
}

warn() {
    msg "WARN" "$@" >&2
}

info() {
    msg "INFO" "$@"
}

main
