#!/usr/bin/env bash

if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "-----"
    echo " Descr: Wrapper for cram2bam and bam2fastq"
    echo " Usage: $(basename $0) <CRAM file>"
    echo " Examp: nohup $(basename $0) <CRAM file> > cram2fastq.log &"
    echo "-----"
    exit 1
fi

cram=$1
bam=$(echo "${cram}" | sed 's/cram$/bam/')

echo "[INFO] Starting with cram2fastq [${cram}]"

#gsutil -m cp ${cram} ./

local_cram=./${cram##*/}
echo "[INFO] In container, using ${local_cram} as input"

./cram2bam "${local_cram}"

./bam2fastq "${bam}"

# At the end you can copy your fastq back into GCS in this location
gsutil -m cp output*.fastq.gz gs://hmf-cram2fastq/fastq/daphne/

echo "[INFO] Finished with cram2fastq" 
