#!/usr/bin/env bash

cram=$1
bam=$2
threads=3
samtools="samtools"

main() {
    info "Starting with $(basename $0)"
    
    ## sanity checks
    command -v "${samtools}" >/dev/null 2>&1 || die "${samtools} not found"
    [[ -f "${cram}" ]] || die "File not found (${cram})"
    [[ "${cram}" =~ cram$ ]] || die "Expected 'cram' extension (${cram})"
    [[ ! -f "${bam}" ]] || die "Output BAM already exists (${bam})"

    ## jobs
    info "Config: Samtools (${samtools})"
    info "Config: Input ${cram}"
    info "Config: Output ${bam}"
    ${samtools} view -O bam -o "${bam}" --threads "${threads}" "${cram}"

    info "Creating flagstat for ${cram}"
    cram_flagstat="${cram}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}"

    info "Creating flagstat for ${bam}"
    bam_flagstat="${bam}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}"

    total_cram=$(cat ${cram_flagstat} | head -1 | cut -d" " -f1)
    total_bam=$(cat ${bam_flagstat} | head -1 | cut -d" " -f1)

    info "File ${cram_flagstat} shows ${total_cram} total reads"
    info "File ${bam_flagstat} shows ${total_bam} total reads"

    info "Running diff on flagstats"
    diff ${cram_flagstat} ${bam_flagstat}
    if [[ $? -ne 0 ]]; then 
        warn "Flagstat diff failed: check result before using downstream!!"
    fi

    info "Finished with $(basename $0)"
}

die() { 
    echo "[ERROR] $(date +"%y%m%d %T") $@" >&2
    exit 1 
}

warn() { 
    echo "[WARN] $(date +"%y%m%d %T") $@" >&2
}

info() { 
    echo "[INFO] $(date +"%y%m%d %T") $@"
}

main
