#!/usr/bin/env bash

cram=$1
threads=3
samtools="samtools"
picard="PicardCommandLine"

fastq_dir="./fastq"
bam=${cram/.cram/.bam}
bucket="hmf-cram2fastq"

main() {
    info "Starting with $(basename $0)"
    info "Config: Cram = ${cram}"
    info "Config: Bam = ${bam}"
    info "Config: Fastq = ${fastq_dir}"
    info "Config: Bucket = ${bucket}"

    ## sanity checks
    command -v "${samtools}" >/dev/null 2>&1 || die "${samtools} not found"
    command -v "${picard}" >/dev/null 2>&1 || die "${picard} not found"
    [[ -f "${cram}" ]] || die "File not found (${cram})"
    [[ "${cram}" =~ (cram|bam)$ ]] || die "Expected 'cram' or 'bam' extension (${cram})"

    ## the magic
    if [[ "${cram}" =~ (cram|bam)$ ]]; then
        echo "[INFO] Converting CRAM to BAM"
        convert_cram_to_bam "${cram}" "${bam}"
    fi
    echo "[INFO] Converting BAM to FASTQ"
    convert_bam_to_fastq "${bam}" "${fastq_dir}"
    echo "[INFO] Copying output fastq to GCP (${bucket})"
    gsutil -m cp "${fastq_dir}/*.fastq.gz" "gs://${bucket}/fastq/stef/"
}

convert_cram_to_bam() {
    local cram=$1 && shift
    local bam=$1 && shift

    info "Converting ${cram} to BAM"
    ${samtools} view -O bam -o "${bam}" --threads "${threads}" "${cram}"

    info "Creating flagstat for ${cram}"
    cram_flagstat="${cram}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}"

    info "Creating flagstat for ${bam}"
    bam_flagstat="${bam}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}"

    total_cram=$(cat ${cram_flagstat} | head -1 | cut -d" " -f1)
    total_bam=$(cat ${bam_flagstat} | head -1 | cut -d" " -f1)

    info "File ${cram_flagstat} shows ${total_cram} total reads"
    info "File ${bam_flagstat} shows ${total_bam} total reads"

    info "Running diff on flagstats"
    diff ${cram_flagstat} ${bam_flagstat} || die "Flagstat diff failed: check result before using downstream!!"

    info "Finished with $(basename $0)"
}

convert_bam_to_fastq() {
    local bam=$1 && shift
    local out_dir=$1 && shift

    info "Converting ${bam} to FASTQ"

    # double check format of RG/ID tags in header
    correct_lane_count=$(samtools view -H "${bam}" | grep ^@RG | grep -vcP "_L00[1-8]_" )
    if [[ "${correct_lane_count}" -gt 1 ]]; then
        echo "[ERROR] There are RG ID header lines in BAM without the expected pattern (_L00[1-8]_):"
        ${samtools} view -H "${bam}" | grep ^@RG
        exit 1
    fi

    echo "[INFO] Running SamToFastq for bam file: $(basename "${bam}")"
    ${picard} SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${bam}"

    echo "[INFO] Renaming fastq files to standard format"
    find "${out_dir}" -name "*.fastq" | while read fastq_path; do
        old_name=$(basename "${fastq_path}")
        new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
        mv "${fastq_path}" "${out_dir}/${new_name}"
        echo "[INFO]   Renamed ${old_name} to ${new_name}"
    done

    echo "[INFO] Compressing fastq files (with pigz)"
    find "${out_dir}" -name "*.fastq" -exec pigz {} +

    echo "[INFO] Output in ${out_dir}"
}

die() { 
    echo "[ERROR] $(date +"%y%m%d %T") $@" >&2
    exit 1 
}

warn() { 
    echo "[WARN] $(date +"%y%m%d %T") $@" >&2
}

info() { 
    echo "[INFO] $(date +"%y%m%d %T") $@"
}

main
