apiVersion: batch/v1
kind: Job
metadata:
  name: ${pod_name}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: ${pod_name}
          image: eu.gcr.io/hmf-build/cram2fastq:1.0
          args: [${cram}, ${bucket}, ${new_name}]
      imagePullSecrets:
        - name: container-registry-reader
      restartPolicy: Never